= HelloBot REST API Guide
Build by "Mojunseo";
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 정의

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|=== 


[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다. +
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다. +
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다. +

[[resources]]
= 리소스

[[resources-chatbot]]
== ChatBot API

챗봇API는 사용자의 입력에 따라 정해진 시나리오를 대답해주는 API입니다.

[[resources-getAccount]]
=== 사용자 정보가져오기

`Get` 요청을 사용해서 생성된 사용자 정보를 가져올 수 있습니다. +
반환 된 Token을 이용하여 리스소에 접근할 수 있습니다.

operation::getAccount[snippets='http-request,http-response,response-fields,links']

[[resources-makeScenario]]
=== 시나리오 만들기

`Get` 요청을 사용해서 미리 정해진 시나리오를 생성할 수 있습니다. +

operation::makeScenario[snippets='http-request,http-response,response-fields,links']

[[resources-chatStart]]
=== 시나리오 시작하기

`Post` 요청을 사용해서 미리 정해진 시나리오를 생성할 수 있습니다. +
시나리오 시작은 Dto를 요구하지 않습니다.

operation::chatStart[snippets='http-request,http-response,response-fields,links']

[[resources-chatResponseButton]]
=== 사용자의 빠른입력(버튼)에 따른 챗봇 응답

`Post` 요청을 사용해서 미리 정해진 시나리오를 진행합니다. +
빠른입력(버튼)을 이용하면 미리 정해둔 값에만 응답합니다.

operation::chatResponseButton[snippets='http-request,http-response,request-fields,response-fields,links']

[[resources-chatResponseFree]]
=== 사용자의 자유입력에 따른 챗봇 응답

`Post` 요청을 사용해서 미리 정해진 시나리오를 진행합니다. +
자유입력 이용하면 미리 정해둔 값과 유사한 경우에 응답합니다.

operation::chatResponseButton[snippets='http-request,http-response,request-fields,response-fields,links']

[[resources-testCodes]]
== 단위/통합테스트

여러 경우에 대비하여 단위 테스트와 통합테스트를 진행했습니다.

[[resources-testCodeCase]]
=== 테스트 케이스

1. 사전에 생성된 Account 계정 정보를 가져오는 API테스트 +
2. 잘못된 토큰을 가지고 허용되지않은 자원에 접근할 경우의 API테스트 +
3. 미리 작성된 시나리오를 생성하는 API테스트 +
4. 채팅 시작시, 응답을 가져오는 API테스트 +
5. 각 대화 Depth(단계)에 따라, 사용자가 빠른선택지를 이용했을 때 응답하는 API테스트 +
6. 각 대화 Depth(단계)에 따라, 사용자가 자유입력형식을 이용했을 때 응답하는 API테스트 +
7. 각 대화 Depth(단계)에 따라, 사용자가 '잘못된' 빠른선택지를 이용했을 때 응답하는 API테스트 +
8. 각 대화 Depth(단계)에 따라, 사용자가 이용한 자유입력이 정해진 응답과 방향이 다를 경우 API테스트 +
9. 각 대화 Depth(단계)에 따른 프로세스 진행시, 온전하지 못한 Dto를 전송할 경우의 API테스트



